apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: basicapp
  name: basicapp
  namespace: myapplication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basicapp
  template:
    metadata:
      labels:
        app: basicapp
    spec:
      containers:
        - image: purvakoushik/django-portfolio:latest
          name: django-portfolio
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: basicapp
  namespace: myapplication
  labels:
    app: basicapp
spec:
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app: basicapp
  type: LoadBalancer
